name: CI/CD Pipeline
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build-and-push:
    # self-hosted: 로컬 노트북 또는 PC에서 Runner를 실행합니다.
    # arc-runner-set: Kubernetes에서 Runner를 실행합니다.
    runs-on: arc-runner-set
    permissions:
      contents: write # Required for semantic-release to push tags/releases
      issues: write # Required for semantic-release to comment on issues
      pull-requests: write # Required for semantic-release to comment on PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish package to NPM
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0' # Use your desired Node version

      - name: Install dependencies
        run: npm clean-install

      - name: Run semantic-release
        env:
          # A GitHub token is still needed for GitHub API interactions (tags, releases)
          GITHUB_TOKEN: ${{ secrets.GITOPS_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # 리포지토리 소유자의 사용자 이름입니다.
          username: ${{ github.repository_owner }}
          # Container Registry Access Token
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # 생성할 이미지에 두 개의 태그를 붙여 줌
          tags: |
            ghcr.io/${{ github.repository }}:latest            
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update GitOps repository
        shell: bash
        env:
          # GitOps Repository Access Token
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          rm -rf gitops
          
          git clone https://github.com/kkw855/react-web-ui-gitops.git gitops
          cd gitops

          if [[ "$OSTYPE" == "darwin"* ]]; then
          sed -i '' "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          else
          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          fi
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          git push -f https://${GIT_TOKEN}@github.com/kkw855/react-web-ui-gitops.git main
